- name: Test with Wokwi
  uses: wokwi/wokwi-ci-action@v1
  with:
    token: ${{ secrets.WOKWI_CLI_TOKEN }}
    path: / # directory with wokwi.toml, relative to repo's root
    timeout: 10000
    expect_text: 'Hello world!'
    fail_text: 'Error'
    serial_log_file: 'log-hello-world.txt' # optional
#    scenario: 'test-hello-world.yaml' # optional
